modelName: "fractal+sphere"
nContrib: 300
modelDType: "default"
fitParameterLimits:
  A_scale: 'auto'
  A_radius: 'auto'
  B_scale: 'auto'
  B_radius: 'auto'
  B_fractal_dim: 
    - 1
    - 3
  B_cor_length: 'auto'
  B_volfraction: 'auto'
staticParameters:
  A_sld: 8.575 # units of 1e-6 A^-2
  A_sld_solvent: 9.469
  B_sld_block: 8.575
  B_sld_solvent: 9.469
maxIter: 1000
convCrit: 1
nRep: 3
nCores: 5
